version: "3"

volumes:
  log:
  pgdata-vol:

services:
  base:
    image: pgconf-app 
    build:
      dockerfile: Dockerfile
      context: .

  web:
    container_name: php
    image: pgconf-app
    env_file:
      - .env
    volumes:
     - log:/var/www/html/storage/logs/
    ports:
     - "8080:80"
    entrypoint: ['app-entrypoint.sh']
 
 
  migrations:
    container_name: migrations
    image: pgconf-app
    env_file:
      - .env
    volumes:
     - log:/var/www/html/storage/logs/

  database:
    container_name: banco
    image: postgres:10
    ports:
          - "5439:5432"
#    deploy: 
#      replicas: 1
    volumes:
      - pgdata-vol:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: pgconf2019

